name: Deploy to ECR

on:
 
  push:
    branches: [ main ]

jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest

   
    steps:

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-access-key-id: AKIA2RJ7XAFNFM3HXWVR
        # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-secret-access-key: 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
        aws-region: ap-northeast-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: comp7940
        IMAGE_TAG: latest
      run: |
        aws ecr-public get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin public.ecr.aws/q1l4k0a8
        docker build -t comp7940:latest .
        docker tag comp7940:latest public.ecr.aws/q1l4k0a8/comp7940:latest
        docker push public.ecr.aws/q1l4k0a8/comp7940:latest

